`timescale 1ns/1ps

module uart_top #(
    parameter int unsigned F_CLK_HZ   = 100_000_000,
    parameter int unsigned BAUD       = 9600,
    parameter int unsigned OVERSAMPLE = 16
) (
    input  logic        sys_clk,
    input  logic        rst,
    input  logic        transmit_btn,
    input  logic [7:0]  tx_data,
    output logic [7:0]  rx_data,
    input  logic        uart_rx_in_async,
    output logic        uart_tx_out,
    output logic        frame_error_sticky
);
    logic clk;
    logic clk_locked;
    logic rst_sync;
    logic tick_16x;
    logic debounced_btn;
    logic transmit_pulse;
    logic uart_rx_sync;
    (* keep = "true" *) logic frame_error;
    logic frame_error_sticky_int;
    logic tx_busy;

    // Clock wizard generated by create_project.tcl
    clk_wiz_0 clock_gen_inst (
        .clk_in1 (sys_clk),
        .reset   (rst),
        .clk_out1(clk),
        .locked  (clk_locked)
    );

    assign rst_sync = rst | ~clk_locked;

    // Debounce the transmit pushbutton
    debouncer #(
        .DEBOUNCE_COUNT(500_000)
    ) debouncer_inst (
        .clk    (clk),
        .rst    (rst_sync),
        .btn_in (transmit_btn),
        .btn_out(debounced_btn)
    );

    // Generate a single-cycle transmit request
    edge_detect_rise edge_tx (
        .clk       (clk),
        .rst       (rst_sync),
        .sig_in    (debounced_btn),
        .rise_pulse(transmit_pulse)
    );

    // Baud-rate enable generator (16x oversampling)
    baud_gen #(
        .F_CLK_HZ  (F_CLK_HZ),
        .BAUD      (BAUD),
        .OVERSAMPLE(OVERSAMPLE)
    ) baud_gen_inst (
        .clk     (clk),
        .rst     (rst_sync),
        .tick_16x(tick_16x)
    );

    // Synchronize the asynchronous RX input
    sync_2ff sync_rx (
        .clk     (clk),
        .rst     (rst_sync),
        .async_in(uart_rx_in_async),
        .sync_out(uart_rx_sync)
    );

    // UART receiver
    uart_rx #(
        .DATA_BITS (8),
        .OVERSAMPLE(OVERSAMPLE)
    ) uart_rx_inst (
        .clk        (clk),
        .rst        (rst_sync),
        .tick_16x   (tick_16x),
        .uart_rx_in (uart_rx_sync),
        .rx_data    (rx_data),
        .frame_error(frame_error),
        .frame_error_sticky(frame_error_sticky_int)
    );

    // UART transmitter
    uart_tx #(
        .DATA_BITS (8),
        .OVERSAMPLE(OVERSAMPLE)
    ) uart_tx_inst (
        .clk        (clk),
        .rst        (rst_sync),
        .tick_16x   (tick_16x),
        .tx_data    (tx_data),
        .transmit   (transmit_pulse),
        .uart_tx_out(uart_tx_out),
        .busy       (tx_busy)
    );

    assign frame_error_sticky = frame_error_sticky_int;

    // frame_error, frame_error_sticky, and tx_busy can be connected to an ILA or LEDs during debug.
endmodule
